project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from tasks.views import index
from quality_control.views import index_1

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tasks/", index),
    path('tasks/', include("tasks.urls")),
    path("quality_control/", index_1),
    path("", include("quality_control.urls")),
]

project_tracker/quality_control/urls.py
from django.urls import path
from . import views

app_name = 'quality_control'

urlpatterns = [
    # path('', views.Index_1_View.as_view(), name='index_1'),
    path('', views.index_1, name='index_1'),
    path('bugs/', views.bug_list, name='bug_list'),
    path('features/', views.feature_list, name='feature_list'),
    path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail'),
    # path('bugs/<int:bug_id>/', views.BugReportDetailView.as_view(), name='bug_detail'),
    path('features/<int:feature_id>/', views.feature_detail, name='feature_detail'),
    # path('features/<int:feature_id>/', views.FeatureRequestView.as_view(), name='feature_detail'),
    path('bugs/new_bug/', views.create_BugReport, name='create_BugReport'),
    path('feature/new_feature/', views.create_FeatureRequest, name='create_FeatureRequest'),
    path('bugs/<int:bug_id>/update/', views.update_BugReport, name='update_BugReport'),
    path('/feature/<int:feature_id>/update/', views.update_FeatureRequest, name='update_FeatureRequest'),
    path('bugs/<int:bug_id>/delete/', views.delete_BugReport, name='delete_BugReport'),
    path('/feature/<int:feature_id>/delete/', views.delete_FeatureRequest, name='delete_FeatureRequest'),
]

project_tracker/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('tasks/', views.index),
    path('tasks/projects/', views.projects_list, name='projects_list'),
    path('tasks/projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('tasks/projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/feedback/', views.feedback_view, name='feedback'),
    path('tasks/project/new/', views.project_create, name="project_create"),
    path('tasks/project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    # ----------------------------------------CBV-------------------------------------------------------
    # path('tasks/project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    # path('tasks/project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('tasks/project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('tasks/project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    # ----------------------------------------CBV-------------------------------------------------------
    # path('tasks/project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    # path('tasks/project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('tasks/project/<int:project_id>/delete', views.delete_project, name="delete_project"),
    path('tasks/project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
]

project_tracker/tasks/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    STATUS_CHOICES = [('New', 'Новая'), ('In_progress', 'В работе'), ('Completed', 'Завершена')]
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    name = models.CharField(max_length=50, default="Page of project")
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    assignee = models.ForeignKey(User, related_name='tasks', on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='New')

    def __str__(self):
        return self.name

project_tracker/tasks/forms.py
from django import forms
from django.forms import ModelForm

from .models import Project
from .models import Task


class FeedbackForm(forms.Form):
    name = forms.CharField(label='Ваше имя', max_length=100)
    email = forms.EmailField(label='Электронная почта')
    message = forms.CharField(widget=forms.Textarea, label="Сообщение")


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description']


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'assignee']

project_tracker/tasks/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from .models import Project, Task
from django.views import View
from django.views.generic import ListView, DetailView
from django.template.loader import render_to_string
from django.shortcuts import render
from .forms import FeedbackForm
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from .forms import ProjectForm
from .forms import TaskForm
from django.views.generic import CreateView
from django.urls import reverse, reverse_lazy


# -----------------------FBV-Function  Based Views---------------------------------
# --------------------index-----------------------------------------------

# Первый вариант
# def index(request):
#     projects_list_url = reverse('tasks:project_list')
#     html = f"<h1>Страница приложения tasks</h1><a href='{projects_list_url}'>Список проектов</a>"
#     return HttpResponse(html)

# Второй вариант
# def index(request):
#     template = render_to_string('tasks/index.html')
#     return HttpResponse(template)

def index(request):
    return render(request, "tasks/index.html")


# ------------------------------------------------------------------------

# def another_page(request):
#     return HttpResponse("Это другая страница приложения tasks.")

# ----------------------project_list---------------------------------

# Первый вариант
# def project_list(request):
#     projects = Project.objects.all()
#     projects_html = '<h1> Список проектов </h1> <ul>'
#     for project in projects:
#         projects_html += f'<li><a href="{project.id}/">{project.name}</a></li>'
#     projects_html += "</ul>"
#     return HttpResponse(projects_html)

def projects_list(request):
    projects = Project.objects.all()
    return render(request, 'tasks/projects_list.html', {'projects_list': projects})


# ----------------------project_detail---------------------------------

# Первый вариант
# def project_detail(request, project_id):
#     project = get_object_or_404(Project, id=project_id)
#     tasks = project.tasks.all()
#     response_html = f'<h1>{project.name}</h1><p>{project.description}</p>'
#     response_html += '<h2>Задачи</h2><ul>'
#     for task in tasks:
#         response_html += f'<li><a href="tasks/{task.id}/">{task.name}</a></li>'
#     response_html += f'</ul>'
#     return HttpResponse(response_html)

def project_detail(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    return render(request, 'tasks/project_detail.html', {'project': project})


# -----------------------task_detail---------------------------------

# Первый вариант
# def task_detail(request, project_id, task_id):
#     project = get_object_or_404(Project, id=project_id)
#     task = get_object_or_404(Task, id=task_id, project=project)
#     response_html = f'<h1>{task.name}</h1><p>{task.description}</p>'
#     return HttpResponse(response_html)

def task_detail(request, project_id, task_id):
    task = get_object_or_404(Task, id=task_id, project_id=project_id)
    return render(request, 'tasks/task_detail.html', {'task': task})


# -----------------------CBV-Class Based Views---------------------------------

# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#         return render(request, 'tasks/index.html')
# class ProjectListView(ListView):
#     model = Project
#     template_name = "tasks/projects_list.html"
#
# class ProjectDetailList(DetailView):
#     model = Project
#     pk_url_kwarg = 'project_id'
#     template_name = 'tasks/project_detail.html'
#
# class TaskDetailView(DetailView):
#     model = Task
#     pk_url_kwarg = 'task_id'
#     template_name = 'tasks/task_detail.html'

def feedback_view(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            # Обработка данных формы
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            recipients = ['info@example.com']
            recipients.append(email)
            send_mail(name, message, email, recipients)
            return redirect('/')
    else:
        form = FeedbackForm()
    return render(request, 'tasks/feedback.html', {'form': form})


def project_create(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:projects_list')
    else:
        form = ProjectForm()
    return render(request, "tasks/project_create.html", {'form': form})


def add_task_to_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.project = project
            task.save()
            return redirect("tasks:project_detail", project_id=project_id)
    else:
        form = TaskForm()
    return render(request, "tasks/add_task.html", {'form': form, "project": project})


def update_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('tasks:project_detail', project_id=project_id)
    else:
        form = ProjectForm(instance=project)
    return render(request, 'tasks/project_update.html', {'form': form, 'project': project})


def update_task(request, project_id, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('tasks:task_detail', project_id=project_id, task_id=task_id)
    else:
        form = TaskForm(instance=task)
    return render(request, 'tasks/task_update.html', {'form': form, 'task': task})


def delete_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    project.delete()
    return redirect('tasks:projects_list')


def delete_task(request, project_id, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.delete()
    return redirect('tasks:project_detail', project_id=project_id)


# -----------------------CBV-реализация Update---------------------------------------------------------------------------------------
# from django.views.generic.edit import UpdateView
# from django.urls import reverse_lazy
# from .models import Project
# from .forms import ProjectForm
#
# class ProjectUpdateView(UpdateView):
#     model = Project
#     form_class = ProjectForm
#     template_name = 'tasks/project_update.html'
#     pk_url_kwarg = 'project_id'
#     success_url = reverse_lazy('tasks:projects_list')
#
# from .models import Task
# from .forms import TaskForm
#
# class TaskUpdateView(UpdateView):
#     model = Task
#     form_class = TaskForm
#     template_name = 'tasks/task_update.html'
#     pk_url_kwarg = 'task_id'
#
#     def get_success_url(self):
#         return reverse_lazy('tasks:task_detail', kwargs={'project_id': self.object.project.id, 'task_id': self.object.id})
# ----------------------------------------------------------------------------------------------------------------------------------

# -----------------------CBV-реализация Create---------------------------------------------------------------------------------------
# class ProjectCreateView(CreateView):
#     model = Project
#     form_class = ProjectForm
#     template_name = 'tasks/project_create.html'
#     success_url = reverse_lazy('tasks:project_list')
#
#
# class TaskCreateView(CreateView):
#     model = Task
#     form_class = TaskForm
#     template_name = 'tasks/add_task.html'
#
#     def form_valid(self, form):
#         form.instance.project = get_object_or_404(Project, pk=self.kwargs['project_id'])
#         return super().form_valid(form)
#
#     def get_success_url(self):
#         return reverse('tasks:project_detail', kwargs={'project_id': self.kwargs['project_id']})
# ----------------------------------------------------------------------------------------------------------------------------------

project_tracker/tasks/templates/tasks/add_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Добавить задачу в проект {{ project.name }}</h2>
<form method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit"> Создать </button>
</form>
</body>
</html>

project_tracker/tasks/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <!-- Общий заголовок для всех страниц -->
        <h1>Проект project-tracker</h1>
    </header>

    <nav>
        <!-- Навигационное меню -->
        <a href="{% url 'tasks:index' %}">Приложение tasks</a>
        <!-- Другие ссылки -->
    </nav>

    <main>
        {% block content %}
        <!-- Основное содержимое страницы -->
        {% endblock %}
    </main>

    <footer>
        <!-- Общий футер для всех страниц -->
    </footer>
</body>
</html>

project_tracker/tasks/templates/tasks/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
</body>
</html>

project_tracker/tasks/templates/tasks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Страница приложения tasks</h1>
<p><a href="{% url 'tasks:projects_list' %}">Список проектов</a></p>
<p><a href="{% url 'quality_control:index_1' %}">Приложение Quality_control</a></p>
</body>
</html>

project_tracker/tasks/templates/tasks/project_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> Создать новый проект</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit"> Сохранить</button>
</form>
</body>
</html>

project_tracker/tasks/templates/tasks/project_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ project.name }}</h1>
    <p>{{ project.description }}</p>
    <p><a href="{% url 'tasks:update_project' project.id%}">Изменить проект</a></p>
    <p><a href="{% url 'tasks:add_task_to_project' project.id %}">Добавить новую задачу</a></p>
    <p><a href="{% url 'tasks:delete_project' project.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот проект?');">Удалить проект</a></p>
    <h2>Задачи в проекте</h2>
    <ul>
        {% for task in project.tasks.all %}
            <li><a href="{% url 'tasks:task_detail' project.id task.id %}">{{ task.name }}</a> - {{ task.status }}</li>
        {% empty %}
            <li>В этом проекте пока нет задач.</li>
        {% endfor %}
    </ul>
</body>
</html>

project_tracker/tasks/templates/tasks/project_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Изменение проекта: {{project.name }}</h2>
<form method="post">
{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Сохранить</button>
</form>
</body>
</html>

project_tracker/tasks/templates/tasks/projects_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Список проектов</h1>
    <p> <a href="{% url 'tasks:project_create' %}"> Создать новый проект</a></p>
    <ul>
        {% for project in projects_list %}
            <li><a href="{% url 'tasks:project_detail' project.id %}">{{ project.name }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

project_tracker/tasks/templates/tasks/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <a href="{% url 'tasks:update_task' project_id=task.project.id task_id=task.id %}">Изменить задачу</a>

<p><a href="{% url 'tasks:delete_task' project_id=task.project.id task_id=task.id %}" onclick="return confirm('Вы уверены, что хотите удалить эту задачу?');">Удалить задачу</a></p>
    <h1>{{ task.name }}</h1>
    <p>{{ task.description }}</p>

</body>
</html>

project_tracker/tasks/templates/tasks/task_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Изменение задачи: {{ task.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
</body>
</html>