project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from tasks.views import index
from quality_control.views import index_1

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tasks/", index),
    path('tasks/', include("tasks.urls")),
    path("quality_control/", index_1),
    path("", include("quality_control.urls")),
]

project_tracker/quality_control/urls.py
from django.urls import path
from . import views

app_name = 'quality_control'

urlpatterns = [
    # path('', views.Index_1_View.as_view(), name='index_1'),
    path('', views.index_1, name='index_1'),
    path('bugs/', views.bug_list, name='bug_list'),
    path('features/', views.feature_list, name='feature_list'),
    path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail'),
    # path('bugs/<int:bug_id>/', views.BugReportDetailView.as_view(), name='bug_detail'),
    path('features/<int:feature_id>/', views.feature_detail, name='feature_detail'),
    # path('features/<int:feature_id>/', views.FeatureRequestView.as_view(), name='feature_detail'),
    path('bugs/new_bug/', views.create_BugReport, name='create_BugReport'),
    path('feature/new_feature/', views.create_FeatureRequest, name='create_FeatureRequest'),
    path('bugs/<int:bug_id>/update/', views.update_BugReport, name='update_BugReport'),
    path('/feature/<int:feature_id>/update/', views.update_FeatureRequest, name='update_FeatureRequest'),
    path('bugs/<int:bug_id>/delete/', views.delete_BugReport, name='delete_BugReport'),
    path('/feature/<int:feature_id>/delete/', views.delete_FeatureRequest, name='delete_FeatureRequest'),
]

project_tracker/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('tasks/', views.index),
    path('tasks/projects/', views.projects_list, name='projects_list'),
    path('tasks/projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('tasks/projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/feedback/', views.feedback_view, name='feedback'),
    path('tasks/project/new/', views.project_create, name="project_create"),
    path('tasks/project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    # ----------------------------------------CBV-------------------------------------------------------
    # path('tasks/project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    # path('tasks/project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('tasks/project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('tasks/project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    # ----------------------------------------CBV-------------------------------------------------------
    # path('tasks/project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    # path('tasks/project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('tasks/project/<int:project_id>/delete', views.delete_project, name="delete_project"),
    path('tasks/project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
]

project_tracker/quality_control/models.py
from django.db import models
from tasks.models import Project, Task


# Create your models here.

class BugReport(models.Model):
    STATUS_CHOICES = [('Новая', 'New'), ('В работе', 'In work'), ('Завершена', 'Finished'),]
    PRIORITY_CHOICES = [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(Project, related_name='BugReport', on_delete=models.CASCADE)
    task = models.ForeignKey(Task, related_name='BugReport', on_delete=models.SET_NULL, null=True, blank=True )
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='Новая')
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


class FeatureRequest(models.Model):
    STATUS_CHOICES = [('Рассмотрение','Рассмотрение'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено')]
    PRIORITY_CHOICES = [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(Project, related_name='FeatureRequest', on_delete=models.CASCADE)
    task = models.ForeignKey(Task, related_name='FeatureRequest', on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='Рассмотрение')
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

project_tracker/quality_control/forms.py
from django import forms
from django.forms import ModelForm
from .models import FeatureRequest, BugReport


class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'project', 'task',
                  'status', 'priority']


class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'project', 'task',
                  'status', 'priority']

project_tracker/quality_control/views.py
from django.urls import reverse
from django.http import HttpResponse
from .models import BugReport, FeatureRequest
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from django.views.generic import DetailView
from .forms import FeatureRequestForm, BugReportForm


# Create your views here.

# ------------------------Function Based Views---------------------------------------------------------------------------------------------------------------

# -----------Function index_1---------------------------------------
# def index_1(request):
#     bugs_list_url = reverse('quality_control:bug_list')
#     feature_list_url = reverse('quality_control:feature_list')
#     html = (f"<h1>Система контроля качества </h1><p><a href='{bugs_list_url}'> Список всех багов</a><p>"
#             f"<p><a href='{feature_list_url}'>Запрос на улучшение</a><p>")
#     return HttpResponse(html)


def index_1(request):
    return render(request, 'quality_control/index_1.html')


# -----------Function bug_list----------------------------------------
# def bug_list(request):
#     bugs = BugReport.objects.all()
#     bugs_html = '<h1> Список отчётов об ошибках </h1><ul>'
#     for bug in bugs:
#         bugs_html += f"<li><a href='{bug.id}/'> {bug.title}</a>     {bug.status}</li>"
#     bugs_html += "</ul>"
#     return HttpResponse(bugs_html)


def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bugs': bugs})


# -----------Function feature_list----------------------------------------
# def feature_list(request):
#     features = FeatureRequest.objects.all()
#     features_html = '<h1> Список отчётов об ошибках </h1><ul>'
#     for feature in features:
#         features_html += f"<li><a href='{feature.id}/'> {feature.title}</a>    {feature.status}</li>"
#     features_html += "</ul>"
#     return HttpResponse(features_html)


def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'features': features})


# -----------Function bug_detail----------------------------------------
# def bug_detail(request, bug_id):
#     bug = get_object_or_404(BugReport, id=bug_id)
#     html = (f'<h1>{bug.title}</h1>'
#             f'<p><i>Описание: </i> {bug.description}</p>'
#             f'<p><i>Статус: </i> {bug.status}</p>'
#             f'<p><i>Приоритет: </i> {bug.priority}</p>'
#             f'<p><i>Проект: </i> {bug.project}</p>'
#             f'<p><i>Задание: </i> {bug.task}</p>')
#     return HttpResponse(html)


def bug_detail(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    return render(request, 'quality_control/bug_detail.html', {'bug': bug})


# -----------Function feature_detail----------------------------------------
# def feature_detail(request, feature_id):
#     feature = get_object_or_404(FeatureRequest, id=feature_id)
#     html = (f'<h1>{feature.title}</h1>'
#             f'<p><i>Описание: </i> {feature.description}</p>'
#             f'<p><i>Статус: </i> {feature.status}</p>'
#             f'<p><i>Приоритет: </i> {feature.priority}</p>'
#             f'<p><i>Проект: </i> {feature.project}</p>'
#             f'<p><i>Задание: </i> {feature.task}</p>')
#     return HttpResponse(html)


def feature_detail(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'feature': feature})


# --------- Function for Forms------------------------------------------------
def create_BugReport(request):
    if request.method == "POST":
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("quality_control:bug_list")
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})


def create_FeatureRequest(request):
    if request.method == "POST":
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("quality_control:feature_list")
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})


# --------- Functions for Update----------------------------------------------------------------------
def update_BugReport(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', bug_id=bug_id)
    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bug_report_update.html', {'bug': bug, 'form': form})


def update_FeatureRequest(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_detail', feature_id=feature_id)
    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/feature_request_update.html', {'feature': feature, 'form': form})

# --------- Functions for Delete----------------------------------------------------------------------

def delete_BugReport(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    bug.delete()
    return redirect('quality_control:bug_list')

def delete_FeatureRequest(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    feature.delete()
    return redirect('quality_control:feature_list')

# ------------------------Class Based Views---------------------------------------------------------------------------------------------------------------
# class Index_1_View(View):
#     def get(self, request, *args, **kwargs):
#         bugs_list_url = reverse('quality_control:bug_list')
#         feature_list_url = reverse('quality_control:feature_list')
#         html = (f"<h1>Система контроля качества </h1><p><a href='{bugs_list_url}'> Список всех багов</a><p>"
#                 f"<p><a href='{feature_list_url}'>Запрос на улучшение</a><p>")
#         return HttpResponse(html)

# class BugReportDetailView(DetailView):
#     model = BugReport
#     pk_url_kwarg = 'bug_id'
#
#     def get(self, request, *args, **kwargs):
#         bug = self.get_object()
#         html = (f'<h1>{bug.title}</h1>'
#             f'<p><i>Описание: </i> {bug.description}</p>'
#             f'<p><i>Статус: </i> {bug.status}</p>'
#             f'<p><i>Приоритет: </i> {bug.priority}</p>'
#             f'<p><i>Проект: </i> {bug.project}</p>'
#             f'<p><i>Задание: </i> {bug.task}</p>')
#         return HttpResponse(html)


# class FeatureRequestView(DetailView):
#     model = FeatureRequest
#     pk_url_kwarg = 'feature_id'
#
#     def get(self, *args, **kwargs):
#         feature = self.get_object()
#         html = (f'<h1>{feature.title}</h1>'
#                 f'<p><i>Описание: </i> {feature.description}</p>'
#                 f'<p><i>Статус: </i> {feature.status}</p>'
#                 f'<p><i>Приоритет: </i> {feature.priority}</p>'
#                 f'<p><i>Проект: </i> {feature.project}</p>'
#                 f'<p><i>Задание: </i> {feature.task}</p>')
#         return HttpResponse(html)

project_tracker/quality_control/templates/quality_control/bug_detail.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
{% extends 'base.html' %}
{% block content %}
<h1>{{bug.title}}</h1>
<p><a href="{% url 'quality_control:update_BugReport' bug.id%}">Изменить отчёт</a>   <a href="{% url 'quality_control:delete_BugReport' bug.id%}">Удалить отчёт</a></p>
    <p><i>Описание: </i> {{bug.description}}</p>
    <p><i>Статус: </i> {{bug.status}}</p>
    <p><i>Приоритет: </i> {{bug.priority}}</p>
    <p><i>Проект: </i> <a href="{% url 'tasks:project_detail' bug.project.id %}">{{ bug.project.name }}</a>  </p>
    <p><i>Задание: </i> <a href="{% url 'tasks:task_detail' bug.project.id bug.task.id %}">{{ bug.task.name }}</a>     <i>Статус:</i>{{bug.task.status}}</p>
{% endblock %}
<!--</body>-->
<!--</html>-->

project_tracker/quality_control/templates/quality_control/bug_list.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
{% extends 'base.html' %}
{% block content %}
<p><a href="{% url 'quality_control:create_BugReport' %}">Создать новый отчёт</a></p>
<h1> Список отчётов об ошибках </h1>
<ul>
    {% for bug in bugs %}
    <li><a href="{% url 'quality_control:bug_detail' bug.id %}">{{ bug.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}
<!--</body>-->
<!--</html>-->

project_tracker/quality_control/templates/quality_control/bug_report_form.html
{% extends 'base.html'%}

{% block content %}
<h2>Создать новый отчёт</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit"> Сохранить</button>
</form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_report_update.html
{% extends 'base.html'%}

{% block content %}
<h2>Изменение Ошибки: {{bug.title}}</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit'> Сохранить</button>
</form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_detail.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
{% extends 'base.html' %}
{% block content %}
<h1>{{feature.title}}</h1>
<p><a href="{% url 'quality_control:update_FeatureRequest' feature.id%}">Изменить запрос</a>  <a href="{% url 'quality_control:delete_FeatureRequest' feature.id%}">Удалить запрос</a></p>
    <p><i>Описание: </i> {{feature.description}}</p>
    <p><i>Статус: </i> {{feature.status}}</p>
    <p><i>Приоритет: </i> {{feature.priority}}</p>
    <p><i>Проект: </i> <a href="{% url 'tasks:project_detail' feature.project.id %}">{{ feature.project.name }}</a>  </p>
    <p><i>Задание: </i> <a href="{% url 'tasks:task_detail' feature.project.id feature.task.id %}">{{ feature.task.name }}</a>     <i>Статус:</i>{{feature.task.status}}</p>
{%  endblock %}
<!--</body>-->
<!--</html>-->

project_tracker/quality_control/templates/quality_control/feature_list.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
{% extends 'base.html' %}
{% block content %}
<p><a href="{% url 'quality_control:create_FeatureRequest' %}">Создать новый запрос</a></p>
<h1> Список запросов </h1>
<ul>
    {% for feature in features %}
    <li><a href="{% url 'quality_control:feature_detail' feature.id %}">{{ feature.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}
<!--</body>-->
<!--</html>-->

project_tracker/quality_control/templates/quality_control/feature_request_form.html
{% extends 'base.html' %}

{% block content %}
<h2>Создать новый запрос</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_request_update.html
{% extends 'base.html'%}

{% block content %}
<h2>Изменение Запроса: {{feature.title}}</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit'> Сохранить</button>
</form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/index_1.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
{% extends 'base.html' %}
{% block content %}
<h1>Система контроля качества </h1>
<p><a href="{% url 'quality_control:bug_list' %}"> Список всех багов</a><p>
<p><a href="{% url 'quality_control:feature_list' %}">Запрос на улучшение</a><p>
{% endblock %}
    <!--</body>-->
<!--</html>-->